---
- name: Install necessary packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - cmake
    - gcc
    - git
    - libffi-dev
    - libfftw3-double3
    - libfftw3-single3
    - libfftw3-long3
    - libfftw3-dev
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - python-pip
    - software-properties-common
    - tar
    - wget

- name: clone git repositories
  git: repo={{ item.repo }} dest={{ item.dest }} clone=yes version={{item.version}}
  with_items:
    - { repo: "https://github.com/haddocking/{{ haddock_app }}.git", dest: "/usr/local/{{ haddock_app }}", version: "HEAD" }
    - { repo: "https://github.com/clMathLibraries/clFFT.git", dest: "/usr/local/clFFT", version: "HEAD" }
    - { repo: "https://github.com/geggo/gpyfft.git", dest: "/usr/local/gpyfft", version: "b462420e19a534d832a9925f01109e80d3431de2" }

- name: wget nvidia driver
  get_url: url={{ nvidia_url }} dest=/usr/local mode=700

- name: unarchive opencl headers
  unarchive: src={{ opencl_url }} dest=/usr/include copy=no
  
- name: copy libOpenCL in /usr/lib
  copy: src=/usr/include/libOpenCL.so dest=/usr/lib
  when: {{ nvidia_driver_version }} == "352.93"
  
- name: install nvidia driver
  command: ./{{ nvidia_driver }} -s --no-kernel-module chdir=/usr/local

- name: install clFFT - configure
  command: cmake CMakeLists.txt chdir=/usr/local/clFFT/src
  env:
    LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu

- name: make install clFFT
  command: make install chdir=/usr/local/clFFT/src
  env:
    LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu

- name: pip install python modules
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - Cython
    - mako
    - numpy
    - scipy
    - virtualenv
    - pyfftw

- name: pip install pyopencl==2015.1
  pip: name=pyopencl version=2015.1 state=present
  when: {{ nvidia_driver_version }} == "319.82"
  
- name: pip install pyopencl
  pip: name=pyopencl state=latest
  when: {{ nvidia_driver_version }} == "352.93"
  
- name: copy again libOpenCL in /usr/lib
  copy: src=/usr/include/libOpenCL.so dest=/usr/lib/libOpenCL.so.1.0.0
  when: {{ nvidia_driver_version }} == "352.93"

- name: install gpyfft
  command: git checkout b462420e19a534d832a9925f01109e80d3431de2 chdir=/usr/local/gpyfft
- command: python setup.py install chdir=/usr/local/gpyfft

- name: pip install {{ haddock_app }}
  pip: name={{ item }} state=present
  with_items:
    - "file:///usr/local/{{ haddock_app }}"

- name: unarchive powerfit examples
  unarchive: src=http://www.lip.pt/~david/powerfit-example.tgz dest=/home copy=no
